### ISSUE TITLE
Turkish i, eth, underdot

### ISSUE THREAD

**Issue by danielgildea** [athreef/TeX-Encode#5]
- `\i`, `\"\i`, etc., are not converted to ı (used in Turkish names), ï, etc.   
- `\dh` should be `ð` (used in Icelandic) but it becomes `ḥ`. It seems like
`\dh` is being parsed as `\d h`, because `\da` gives an a with underdot, `\db`
gives a b with underdot, etc.
- On the other hand, `{\d e}` should give an e with underdot, but doesn't.

**Comment by a3f** [comment]
Sorry, this slipped through the cracks. Feel free to send patches to address these.

**Comment by danielgildea** [comment]
Patch adding dotless i and fixing eth below.

But the accents whose commands are letters in Latex don't seem to work at all.
For example, `\cc` is converted to `ç`, but `\cc` is not valid Latex.
In Latex you would say `\c c` or `\c{c}`, but those aren't handled by this module.



~~~
diff --git a/lib/TeX/Encode/charmap.pm b/lib/TeX/Encode/charmap.pm
index 44440f8..c3791af 100644
--- a/lib/TeX/Encode/charmap.pm
+++ b/lib/TeX/Encode/charmap.pm
@@ -91,6 +91,7 @@ chr(0x00f8) => '\\o', # ø
 chr(0x00fe) => '\\th', # þ
 chr(0x0110) => '\\DJ', # Đ
 chr(0x0111) => '\\dj', # đ
+chr(0x0131) => '\\i', # ı
 chr(0x0132) => '\\IJ', # Ĳ
 chr(0x0133) => '\\ij', # ĳ
 chr(0x0141) => '\\L', # Ł
@@ -543,7 +544,6 @@ chr(0x1e29) => "\\ch", # ḩ
 chr(0x1e23) => "\\\.h", # ḣ
 chr(0x0127) => "\\\=h", # ħ
 chr(0x1e96) => "\\bh", # ẖ
-chr(0x1e25) => "\\dh", # ḥ
 
 ### i
 

~~~

**Comment by a3f** [comment]
> Patch adding dotless i and fixing eth below.

I've just pushed TeX::Encode v2.006 with your changes. Thanks and sorry for the delay.

> But the accents whose commands are letters in Latex don't seem to work at all.
For example, \cc is converted to ç, but \cc is not valid Latex.
In Latex you would say \c c or \c{c}, but those aren't handled by this module.

Ye, there's still work to do, but I don't actively work on this anymore. Pull requests are however very welcome.
