### ISSUE TITLE
Character 0x00c5 encoded to '\\AA' as well as '\\rA' (similar for 0x00e5)

### ISSUE THREAD

**Issue by ehuelsmann** [athreef/TeX-Encode#6]
On [line 81 of charmap](https://github.com/athreef/TeX-Encode/blob/master/lib/TeX/Encode/charmap.pm#L81) the character 0x00c5 is encoded to '\\AA' (which is correct), but later (on [line 196](https://github.com/athreef/TeX-Encode/blob/master/lib/TeX/Encode/charmap.pm#L196)) it''s encoded to '\\rA' which is incorrect.

With different line numbers, the same applies to character 0x00e5.

**Comment by a3f** [comment]
Thanks for reporting and fixing this. I just pushed [v2.007](https://github.com/athreef/TeX-Encode/releases/tag/v2.007) to PAUSE.
